FROM golang:1.14

WORKDIR /go/src/bench

RUN apt-get update && apt-get install -y wget default-mysql-client

COPY ./isucon10-qualify/bench/go.mod .
COPY ./isucon10-qualify/bench/go.sum .
RUN go mod download
COPY isucon10-qualify/bench/ .
RUN make all
