FROM golang:1.14

EXPOSE 1323

WORKDIR /go/src/isuumo

RUN apt-get update && apt-get install -y wget default-mysql-client

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY . .
RUN make isuumo
