FROM golang:1.14

EXPOSE 1323

WORKDIR /go/src/isuumo

RUN apt-get update && apt-get install -y wget default-mysql-client

COPY ./isucon10-qualify/webapp/go/go.mod .
COPY ./isucon10-qualify/webapp/go/go.sum .
RUN go mod download
COPY isucon10-qualify/webapp/go/ .
RUN make isuumo
